services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab.local
    restart: always
    ports:
      - "8080:80"
      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: "256m"
    networks:
      - devsecops_net

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: always
    depends_on:
      - sonarqube_db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - devsecops_net

  sonarqube_db:
    image: postgres:15
    container_name: sonarqube_db
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
    networks:
      - devsecops_net

  infisical_db:
    image: postgres:14-alpine
    container_name: infisical-db
    restart: always
    env_file: .dev.env
    volumes:
      - infisical_db_data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready --username=infisical && psql --username=infisical --list"
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - devsecops_net

  infisical_redis:
    image: redis
    container_name: infisical-dev-redis
    env_file: .dev.env
    restart: always
    networks:
      - devsecops_net
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - infisical_redis_data:/data

  infisical:
    image: infisical/infisical:latest
    pull_policy: always
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      infisical_db:
        condition: service_healthy
      infisical_redis:
        condition: service_started
    ports:
      - "8081:8080"
    env_file: .dev.env
    environment:
      - NODE_ENV=production
    networks:
      - devsecops_net

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_db_data:
  infisical_db_data:
  infisical_redis_data:

networks:
  devsecops_net:
    driver: bridge
